- example/ios/Podfile
- ios/RNBLEPrinter.m
- ios/RNNetPrinter.m
- ios/RNUSBPrinter.m
- package.json
- rn-receipt-printer-utils.podspec
- src/index.ts
- tsconfig.build.json
- Now @tillpos/rn-receipt-printer-utils, can be imported in pod spec file
- Send hex values to the printer from ios
Issue: #XXX
Not tested, I'm on ubuntu :smile:
> Ios changes and podspec package name support

- android/src/main/java/com/pinmi/react/printer/adapter/NetPrinterAdapter.java
Invoke success and error callbacks from connectAndSend method
Issue: #XXX
> Invoke success and error callbacks

- ios/RNNetPrinter.m
Added `connectAndSend` to ios implementation.
Issue: #XXX
> feat(ios): added connectAndSend implementation

- android/src/main/java/com/pinmi/react/printer/RNBLEPrinterModule.java
- android/src/main/java/com/pinmi/react/printer/RNNetPrinterModule.java
- android/src/main/java/com/pinmi/react/printer/adapter/BLEPrinterAdapter.java
- android/src/main/java/com/pinmi/react/printer/adapter/NetPrinterAdapter.java
- android/src/main/java/com/pinmi/react/printer/adapter/PrinterAdapter.java
- android/src/main/java/com/pinmi/react/printer/adapter/USBPrinterAdapter.java
Support bluetooth printing in android
Issue: #XXX
> (#3) Support bluetooth printing in android

- example/ios/Podfile.lock
- example/src/App.tsx
- ios/PrinterSDK/PrinterSDK.h
- ios/RNBLEPrinter.h
- ios/RNBLEPrinter.m
- ios/RNNetPrinter.h
- ios/RNNetPrinter.m
- ios/RNUSBPrinter.h
- ios/RNUSBPrinter.m
- ios/utils/EpsonUtils.h
- ios/utils/EpsonUtils.m
- ios/utils/NSDataAdditions.h
- ios/utils/NSDataAdditions.m
- package.json
- src/index.ts
- yarn.lock
Epson SDK iOS v2.19.0
Issue: #XXX
> (#1) Migrate to Epson SDK iOS

- package.json
- tillpos-rn-receipt-printer-utils.podspec
Add support for x8664
Issue: #XXX
> Add support for x8664

- ios/RNBLEPrinter.m
- ios/RNNetPrinter.m
- ios/RNUSBPrinter.m
- ios/adapters/epson/BLEPrinterEpsonAdapter.m
- ios/adapters/epson/NetPrinterEpsonAdapter.m
- ios/adapters/generic/BLEPrinterGenericAdapter.m
- ios/adapters/generic/NetPrinterGenericAdapter.m
- ios/adapters/generic/USBPrinterGenericAdapter.m
- package.json
> Async printing in ios

- example/src/App.tsx
- ios/adapters/epson/BLEPrinterEpsonAdapter.m
- ios/adapters/epson/NetPrinterEpsonAdapter.h
- ios/adapters/epson/NetPrinterEpsonAdapter.m
This change cause the net printer adapter to disconnect if an error is thrown(in case the connection attempt succeeded) and also retry connecting twice after the initial attempt
> Failed send data fix

- package.json
Update package version to 0.2.2
Issue: #XXX
> chore: updated the package version 0.2.2

- example/src/App.tsx
- ios/adapters/epson/NetPrinterEpsonAdapter.m
- package.json
- src/index.ts
> fix: printing timeout change

- example/src/App.tsx
- ios/adapters/epson/NetPrinterEpsonAdapter.m
- package.json
- src/index.ts
Reverts hitz-group/rn-receipt-printer-utils#22
> Revert "fix: printing timeout change"

- example/src/App.tsx
- ios/adapters/epson/NetPrinterEpsonAdapter.m
- src/index.ts
> Printing timeout change

- package.json
> chore: release 0.2.5

- example/src/App.tsx
- ios/adapters/epson/NetPrinterEpsonAdapter.h
- ios/adapters/epson/NetPrinterEpsonAdapter.m
- package.json
**Issue:**
- `ReceiveEventDelegate` function not being called
- `NetPrinterEpsonAdapter` ref, being in `setReceiveEventDelegate` existing in the `Epos2Printer` instance, and `*printer` ref existing in the NetPrinterEpsonAdapter instance
**Issue Assumption:**
- without `          [printer disconnect]; ` being called, the printer is stuck
- without `    [printerObj setReceiveEventDelegate:nil];` the printerObj and the `NetPrinterEpsonAdapter object` are not being garbage collected and cause memory leak
**Solution:**
- lock connectAndSend for one printer [IP] if another connectAndSend (of a different `NetPrinterEpsonAdapter object` but same IP is running
> - use @syncronize(code-block-id) to syncronise initialise and access the `printerDictionary`
> - use …
> Ganesh tillx/scoped printer

- package.json
> chore: increase package version

- package.json
> chore: set version to 0.2.8

- ios/adapters/epson/NetPrinterEpsonAdapter.m
- package.json
> Ganesh till x/ensure disconnect dealloc

- android/src/main/java/com/pinmi/react/printer/RNBLEPrinterModule.java
- android/src/main/java/com/pinmi/react/printer/RNNetPrinterModule.java
Added missing arguments to Android's Java classes to fix the crash.
Issue: #XXX
> fix:Add missing series argument for java classes

- package.json
> chore: release 0.3.0

- package.json
> chore: release 0.3.1

- example/ios/Podfile.lock
- package.json
- yarn.lock
> chore: upgrade `esc-pos-printer` dep to `4.1.4` to fix android crash
